read_length: 4096
sample_frequency: 44100

yin:
    threshold: 0.05
    num_display: 300
    
cepstrum:
    num_display: 300

note:
    num_display: 300    

plots:
    y_linear: 65000
    freq_min: 20
    freq_max: 1000

pitch:
    num_display: 300
    power_sensitivity: 0.05
